### ISSUE TITLE
Segment kliencki

### ISSUE THREAD

**Issue by pkijas** [amantus/Portal#1]

**Comment by amantus** [comment]
1) Osoby poszukujące pracy. Koncentrujemy się na dwóch grupach: pracownicy fizyczni bez kwalifikacji oraz  baza fachowców, absolwentów szkół zawodowych i technicznych (np. mechanicy, spawacze).
2) Pracodawcy, poszukujący pracowników - specjalistów.
3) Szkoły udostępniające bazę absolwentów szkół  zawodowych i technicznych 

Opłata będzie pobierana od firm, którzy szukają pracowników.
